DATASET_HF: "AqsaK/testdataHW5"
HF_MODEL_NAME: "AqsaK/donut_1880_exp_subset"
PROJECT_NAME: "Donut-subset-1880"
EXPERIMENT_NAME: "exp_run-2"

MAX_EPOCHS: 5
VAL_CHECK_INTERVAL: 0.2 # how many times we want to validate during an epoch
CHECK_VAL_EVERY_N_EPOCH: 1
GRADIENT_CLIP_VAL: 1.0
NUM_TRAINING_SAMPLES_PER_EPOCH: 1190
LR: 3e-5
TRAIN_BATCH_SIZES: 128
VAL_BATCH_SIZES: 64
# SEED: 2022
NUM_NODES: 1
WARMUP_STEPS: 300 # 800/8*30/10, 10%
RESULT_PATH: "./result"
VERBOSE: True