DATASET_HF: "AqsaK/testdataHW4"
HF_MODEL_NAME: "AqsaK/donut-model-finetuned-1880-HW" # whole dataset with FN EN and all other keys 
PROMPT_TOKEN: "<s_cord-v2>"
EVALUATION_SPLIT: "test"
EVALUATION_RESULT_PATH: "test_evaluation_results.json"