repo_id: "AqsaK/testdataHW4"
readme_path: "README.md"
dataset_infos_path: "dataset_infos.json"
gitattributes_path: ".gitattributes"
train_parquet_path: "./train.parquet"
val_parquet_path: "./validation.parquet"
test_parquet_path: "./test.parquet"