repo_id: "AqsaK/testdataHW2"
readme_path: "README.md"
dataset_infos_path: "dataset_infos.json"
gitattributes_path: ".gitattributes"
train_parquet_path: "./train.parquet"
val_parquet_path: "./val.parquet"
test_parquet_path: "./test.parquet"